name: shopmanager_mobile_app
description: "Shop manager mobile app."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  logger: ^2.5.0
  json_annotation: ^4.9.0
  get_it: ^9.1.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  http_mock_adapter: ^0.6.1
  shared_preferences: ^2.5.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  meta: ^1.16.0
  formz: ^0.8.0
  flow_builder: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  retrofit_generator: ^10.2.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  firebase_core_platform_interface: ^6.0.2
  firebase_auth_platform_interface: ^8.1.4
  rename: ^3.1.0

flutter:
  
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/sm/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
